language:
  - ruby
  - node_js
rvm:
  - 2.2.3

node_js:
  - "0.10"

before_script:
  - psql -c 'create database final_project_test;' -U postgres
  - npm install
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 3

script:
 - bundle exec rspec spec
 - npm test --single-run


